import type { TaskPrTemplateSections, SprintPrTemplateSections } from "../../../contracts/app-types.js";
import { formatCostUsd, formatDurationMs, formatIsoTimestamp, formatTokenCount, providerDisplayName } from "./pr-description-format-utils.js";

export type { TaskPrTemplateSections, SprintPrTemplateSections };

const FOOTER = "---\n*🤖 Generated by [Code UX](https://github.com/codeux-ai/codeux)*";

export interface PrUsageStats {
  invocationCount: number;
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  totalTokens: number;
  toolCallCount: number;
  activeTimeMs: number;
  /** Sum across API/billed invocations only. Null when nothing was billed. */
  costUsd: number | null;
  /** Invocations that ran via a metered API key. */
  billedInvocationCount: number;
  /** Invocations that ran via a flat-fee login (local auth / dashboard login), or any Jules invocation. */
  subscriptionInvocationCount: number;
}

export interface PrQaFinding {
  summary: string | null;
  findings: string[];
  outcome: string | null;
  reviewer: string | null;
  finishedAt: string | null;
}

export interface TaskPrComposerInput {
  taskId: string;
  taskTitle: string;
  taskPrompt: string;
  provider: string;
  model: string | null;
  sprintGoal?: string | null;
  sprintNumber?: number | null;
  sprintName?: string | null;
  featureBranch: string;
  workerBranch: string;
  startedAt: string | null;
  finishedAt: string | null;
  durationMs: number | null;
  usage: PrUsageStats | null;
  /** null => QA has not run yet at PR-creation time; render a pending placeholder. */
  qa: PrQaFinding | null;
  sections: TaskPrTemplateSections;
}

export interface SprintPrSubtaskSummary {
  id: string;
  title: string;
  provider?: string | null;
  model?: string | null;
  prUrl?: string | null;
  completed: boolean;
}

export interface SprintPrComposerInput {
  sprintId: string;
  sprintNumber?: number | null;
  sprintName?: string | null;
  sprintGoal: string;
  sprintOriginalPrompt?: string | null;
  defaultBranch: string;
  featureBranch: string;
  subtasks: SprintPrSubtaskSummary[];
  planning: { provider: string | null; model: string | null; usage: PrUsageStats | null } | null;
  aggregateUsage: PrUsageStats | null;
  startedAt: string | null;
  finishedAt: string | null;
  qa: PrQaFinding | null;
  sections: SprintPrTemplateSections;
}

function sprintLabel(sprintNumber?: number | null, sprintName?: string | null): string {
  if (sprintName && sprintNumber != null) return `Sprint ${sprintNumber} · ${sprintName}`;
  if (sprintName) return sprintName;
  if (sprintNumber != null) return `Sprint ${sprintNumber}`;
  return "this sprint";
}

function renderFindingsList(findings: string[]): string {
  const items = findings.map((f) => `- ${f}`).join("\n");
  if (findings.length > 3) {
    return `<details>\n<summary>${findings.length} findings</summary>\n\n${items}\n</details>`;
  }
  return items;
}

function renderQaBlock(qa: PrQaFinding | null, pendingMessage: string): string {
  if (!qa) return pendingMessage;

  const lines: string[] = [];
  if (qa.outcome) lines.push(`**Outcome:** ${qa.outcome}`);
  if (qa.summary) lines.push(qa.summary.trim());
  if (qa.findings.length > 0) lines.push(renderFindingsList(qa.findings));
  if (lines.length === 0) lines.push("No findings recorded.");
  return lines.join("\n\n");
}

function renderUsageBlock(usage: PrUsageStats | null, heading: string): string {
  if (!usage || usage.invocationCount === 0) {
    return `${heading ? `${heading}\n\n` : ""}_No usage data recorded._`;
  }

  const rows: string[] = [
    "| Metric | Value |",
    "|---|---|",
    `| Input tokens | ${formatTokenCount(usage.inputTokens)} |`,
    `| Cached input tokens | ${formatTokenCount(usage.cachedInputTokens)} |`,
    `| Output tokens | ${formatTokenCount(usage.outputTokens)} |`,
    `| Total tokens | ${formatTokenCount(usage.totalTokens)} |`,
    `| Invocations | ${formatTokenCount(usage.invocationCount)} |`,
    `| Tool calls | ${formatTokenCount(usage.toolCallCount)} |`,
    `| Active time | ${formatDurationMs(usage.activeTimeMs)} |`,
  ];

  const costLabel = formatCostUsd(usage.costUsd);
  const noteLines: string[] = [];
  if (usage.billedInvocationCount > 0 && costLabel) {
    noteLines.push(`**Est. cost (API-billed):** ${costLabel}`);
  }
  if (usage.subscriptionInvocationCount > 0) {
    noteLines.push(
      `ℹ️ ${usage.subscriptionInvocationCount} invocation(s) ran via subscription/local login — not metered, no additional cost.`,
    );
  }

  const parts = [rows.join("\n")];
  if (noteLines.length > 0) parts.push(noteLines.join("\n"));

  return `${heading ? `${heading}\n\n` : ""}${parts.join("\n\n")}`;
}

export function composeTaskPrTitle(input: Pick<TaskPrComposerInput, "taskTitle" | "provider">): string {
  return `${input.taskTitle} (${input.provider})`;
}

export function composeSprintPrTitle(
  input: Pick<SprintPrComposerInput, "sprintNumber" | "sprintName" | "featureBranch" | "defaultBranch">,
): string {
  const label = input.sprintName
    ? `Sprint ${input.sprintNumber ?? "?"}: ${input.sprintName}`
    : `Sprint ${input.sprintNumber ?? "?"}`;
  return `${label} — merge ${input.featureBranch} into ${input.defaultBranch}`;
}

export function composeTaskPrBody(input: TaskPrComposerInput): string {
  const { sections } = input;
  const parts: string[] = [];

  parts.push(`## 🧩 Task: ${input.taskTitle}\n> Automated task PR opened by Code UX for \`${input.taskId}\`.`);

  if (sections.summary) {
    const lines = [`**Sprint:** ${sprintLabel(input.sprintNumber, input.sprintName)}  ·  **Task:** \`${input.taskId}\``];
    if (input.sprintGoal?.trim()) {
      lines.push(`> ${input.sprintGoal.trim().replace(/\n+/g, "\n> ")}`);
    }
    parts.push(`### 📋 Summary\n${lines.join("\n\n")}`);
  }

  if (sections.modelAndProvider) {
    parts.push(
      `### 🤖 Model & Provider\n\n| | |\n|---|---|\n| Provider | ${providerDisplayName(input.provider)} |\n| Model | \`${input.model || "unknown"}\` |`,
    );
  }

  if (sections.timing) {
    parts.push(
      `### ⏱️ Timing\n\n| | |\n|---|---|\n| Started | ${formatIsoTimestamp(input.startedAt)} |\n| Finished | ${formatIsoTimestamp(input.finishedAt)} |\n| Duration | ${formatDurationMs(input.durationMs)} |`,
    );
  }

  if (sections.tokenUsage) {
    parts.push(renderUsageBlock(input.usage, "### 📊 Token Usage"));
  }

  if (sections.qaFindings) {
    const qaBody = renderQaBlock(
      input.qa,
      "⏳ QA review runs after this PR is opened. Check the task card in the dashboard for the outcome once it lands.",
    );
    parts.push(`### ✅ QA Review\n\n${qaBody}`);
  }

  if (sections.fullPrompt) {
    parts.push(`<details>\n<summary>📝 Full Task Prompt</summary>\n\n\`\`\`\n${input.taskPrompt}\n\`\`\`\n</details>`);
  }

  if (sections.branchInfo) {
    parts.push(`<details>\n<summary>🌿 Branch Info</summary>\n\nBase: \`${input.featureBranch}\`\nHead: \`${input.workerBranch}\`\n</details>`);
  }

  parts.push(FOOTER);

  return parts.join("\n\n");
}

export function composeSprintPrBody(input: SprintPrComposerInput): string {
  const { sections } = input;
  const parts: string[] = [];

  const label = sprintLabel(input.sprintNumber, input.sprintName);
  parts.push(`## 🚀 Sprint Completion: ${label}\n> Automated sprint completion PR opened by Code UX.`);

  const completedCount = input.subtasks.filter((t) => t.completed).length;
  const providerCounts = new Map<string, number>();
  for (const task of input.subtasks) {
    if (!task.provider) continue;
    providerCounts.set(task.provider, (providerCounts.get(task.provider) || 0) + 1);
  }
  const providerStatsLine = Array.from(providerCounts.entries())
    .map(([provider, count]) => `${count} by ${provider}`)
    .join(" · ");

  if (sections.summary) {
    parts.push(`### 📋 Summary\n**Sprint:** ${label}   **Tasks:** ${completedCount}/${input.subtasks.length} completed`);
  }

  if (sections.planningModel) {
    if (input.planning) {
      const planningLines = [
        "| | |",
        "|---|---|",
        `| Planning provider | ${providerDisplayName(input.planning.provider)} |`,
        `| Planning model | \`${input.planning.model || "unknown"}\` |`,
      ].join("\n");
      const planningUsage = input.planning.usage ? `\n\n${renderUsageBlock(input.planning.usage, "")}` : "";
      parts.push(`### 🧭 Planning\n\n${planningLines}${planningUsage}`);
    } else {
      parts.push("### 🧭 Planning\n\n_No planning invocation recorded for this sprint._");
    }
  }

  if (sections.mainPrompt) {
    const prompt = (input.sprintOriginalPrompt?.trim() || input.sprintGoal?.trim() || "No prompt recorded.");
    parts.push(`<details>\n<summary>🎯 Original Sprint Prompt</summary>\n\n${prompt}\n</details>`);
  }

  if (sections.taskChecklist) {
    const checklist = input.subtasks
      .map((task) => {
        const checkbox = task.completed ? "[x]" : "[ ]";
        const providerStr = task.provider ? ` — \`${task.provider}\`` : "";
        const prStr = task.prUrl ? ` ([PR](${task.prUrl}))` : "";
        return `- ${checkbox} **${task.id}**: ${task.title}${providerStr}${prStr}`;
      })
      .join("\n");
    parts.push(`### ✅ Task Checklist\n\n${checklist}`);
  }

  if (sections.providerBreakdown && providerStatsLine) {
    parts.push(`### 👥 Provider Breakdown\n\n${providerStatsLine}`);
  }

  if (sections.timing) {
    parts.push(
      `### ⏱️ Sprint Timing\n\n| | |\n|---|---|\n| Started | ${formatIsoTimestamp(input.startedAt)} |\n| Finished | ${formatIsoTimestamp(input.finishedAt)} |\n| Duration | ${formatDurationMs(
        input.startedAt && input.finishedAt ? new Date(input.finishedAt).getTime() - new Date(input.startedAt).getTime() : null,
      )} |`,
    );
  }

  if (sections.tokenUsage) {
    parts.push(renderUsageBlock(input.aggregateUsage, "### 📊 Aggregate CLI Token Usage"));
  }

  if (sections.qaFindings) {
    const qaBody = renderQaBlock(input.qa, "_Sprint completion did not run a QA review._");
    parts.push(`### 🕵️ QA Review Summary\n\n${qaBody}`);
  }

  if (sections.branchInfo) {
    parts.push(`<details>\n<summary>🌿 Branch Info</summary>\n\nBase: \`${input.defaultBranch}\`\nHead: \`${input.featureBranch}\`\n</details>`);
  }

  parts.push(FOOTER);

  return parts.join("\n\n");
}
