import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { AppDbStorage } from "../../../src/repositories/app-db-storage.js";
import { ProjectManagementRepository } from "../../../src/repositories/project-management-repository.js";
import { AutomationCredentialRepository } from "../../../src/repositories/automation-credential-repository.js";
import { MountedKeyFileProvider } from "../../../src/infrastructure/security/mounted-key-file-provider.js";
import { EncryptedSqliteSecretStore } from "../../../src/infrastructure/security/encrypted-sqlite-secret-store.js";
import { CredentialBroker } from "../../../src/services/credentials/credential-broker.js";

const dirs:string[]=[];
async function fixture(){const dir=await mkdtemp(join(tmpdir(),"credential-test-"));dirs.push(dir);const dbPath=join(dir,"app.db");const keyPath=join(dir,"root.key");await writeFile(keyPath,Buffer.alloc(32,9).toString("base64"),{mode:0o600});const storage=new AppDbStorage(dbPath);const projects=new ProjectManagementRepository(storage);const first=projects.createProject({name:"First",sourceType:"local",sourceRef:join(dir,"first")});const second=projects.createProject({name:"Second",sourceType:"local",sourceRef:join(dir,"second")});const repository=new AutomationCredentialRepository(storage);const provider=new MountedKeyFileProvider(keyPath);const broker=new CredentialBroker(repository,new EncryptedSqliteSecretStore(repository,provider),provider);return{dir,dbPath,storage,repository,broker,first,second};}
afterEach(async()=>{await Promise.all(dirs.splice(0).map((dir)=>rm(dir,{recursive:true,force:true})))});

describe("automation credential repository and broker",()=>{
  it("persists only encrypted material, resolves capabilities, rotates, and audits metadata",async()=>{const f=await fixture();const secret="plain-secret-marker";const created=await f.broker.create(f.first.id,{name:"Token",kind:"api-token",value:secret,capabilities:["read"]});expect(JSON.stringify(created)).not.toContain(secret);const persisted=f.storage.getDatabase().prepare("SELECT * FROM automation_credential_secrets WHERE credential_id=?").get(created.id) as Record<string,unknown>;expect(JSON.stringify(persisted)).not.toContain(secret);f.broker.bind(f.first.id,created.id,"node.http",["read"]);expect((await f.broker.resolve({projectId:f.first.id,bindingKey:"node.http",capability:"read",workspaceId:"run"})).value).toBe(secret);const rotated=await f.broker.rotate(f.first.id,created.id,"replacement");expect(rotated.version).toBe(2);expect((await f.broker.resolve({projectId:f.first.id,bindingKey:"node.http",capability:"read",workspaceId:"run"})).value).toBe("replacement");const event=f.storage.getDatabase().prepare("SELECT * FROM automation_credential_access_events ORDER BY created_at DESC LIMIT 1").get() as Record<string,unknown>;expect(JSON.stringify(event)).not.toContain(secret);expect(f.storage.getDatabase().prepare("SELECT COUNT(*) AS count FROM automation_credential_rotations").get()).toMatchObject({count:1});f.storage.close();});
  it("fails closed for cross-project, revoked, missing, and insecure providers",async()=>{const f=await fixture();const created=await f.broker.create(f.first.id,{name:"Token",kind:"api-token",value:"secret",capabilities:["read"]});expect(()=>f.broker.bind(f.second.id,created.id,"node.http",["read"])).toThrow(/not available/);f.broker.bind(f.first.id,created.id,"node.http",["read"]);f.broker.revoke(f.first.id,created.id);await expect(f.broker.resolve({projectId:f.first.id,bindingKey:"node.http",capability:"read",workspaceId:"run"})).rejects.toThrow(/not active/);const insecurePath=join(f.dir,"insecure.key");await writeFile(insecurePath,Buffer.alloc(32,4).toString("base64"),{mode:0o644});const insecureHealth=await new MountedKeyFileProvider(insecurePath).health();expect(insecureHealth).toMatchObject({available:false,secure:false});f.storage.close();const unavailable=new MountedKeyFileProvider(undefined);expect((await unavailable.health()).available).toBe(false);});
  it("requires explicit project allowlists and re-encrypts promoted credentials",async()=>{const f=await fixture();await expect(f.broker.create(f.first.id,{name:"Global",kind:"token",value:"secret",scope:"global",allowedProjectIds:[f.second.id],capabilities:["read"]})).rejects.toThrow(/explicit allowlist/);const projectCredential=await f.broker.create(f.first.id,{name:"Promoted",kind:"token",value:"secret",capabilities:["read"]});const promoted=await f.broker.promote(f.first.id,projectCredential.id,[f.first.id,f.second.id]);expect(promoted.scope).toBe("global");f.broker.bind(f.second.id,promoted.id,"node.global",["read"]);expect((await f.broker.resolve({projectId:f.second.id,bindingKey:"node.global",capability:"read",workspaceId:"run"})).value).toBe("secret");f.storage.close();});
});
