#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ErrorCode,
  ListToolsRequestSchema,
  McpError,
} from "@modelcontextprotocol/sdk/types.js";
import axios from "axios";
import dotenv from "dotenv";

dotenv.config();

const API_KEY = process.env.JULES_API_KEY || process.env.JULES_KEY;
const BASE_URL = "https://jules.googleapis.com/v1alpha";

if (!API_KEY) {
  console.error("JULES_API_KEY environment variable is required");
  process.exit(1);
}

class JulesAgentServer {
  private server: Server;
  private axiosInstance: any;

  constructor() {
    this.server = new Server(
      {
        name: "jules-agent",
        version: "1.0.0",
      },
      {
        capabilities: {
          tools: {},
        },
      }
    );

    this.axiosInstance = axios.create({
      baseURL: BASE_URL,
      headers: {
        "X-Goog-Api-Key": API_KEY,
        "Content-Type": "application/json",
      },
    });

    this.setupToolHandlers();
    
    // Error handling
    this.server.onerror = (error) => console.error("[MCP Error]", error);
    process.on("SIGINT", async () => {
      await this.server.close();
      process.exit(0);
    });
  }

  private setupToolHandlers() {
    this.server.setRequestHandler(ListToolsRequestSchema, async () => ({
      tools: [
        {
          name: "getSource",
          description: "Get details of a specific source (e.g., a GitHub repository).",
          inputSchema: {
            type: "object",
            properties: {
              sourceId: { type: "string", description: "The ID of the source (e.g., 'github/owner/repo')." },
            },
            required: ["sourceId"],
          },
        },
        {
          name: "listSources",
          description: "List available sources with optional filtering and pagination.",
          inputSchema: {
            type: "object",
            properties: {
              filter: { type: "string", description: "Filtering criteria." },
              pageSize: { type: "number", description: "Maximum number of sources to return." },
              pageToken: { type: "string", description: "Token for pagination." },
            },
          },
        },
        {
          name: "listAllSources",
          description: "Convenience tool to list all available sources by automatically handling pagination.",
          inputSchema: {
            type: "object",
            properties: {
              filter: { type: "string", description: "Filtering criteria." },
            },
          },
        },
        {
          name: "createSession",
          description: "Create a new session to interact with an agent on a specific source.",
          inputSchema: {
            type: "object",
            properties: {
              prompt: { type: "string", description: "The initial prompt for the agent." },
              source: { type: "string", description: "The source name (e.g., 'sources/github/owner/repo')." },
              startingBranch: { type: "string", description: "Optional starting branch." },
              title: { type: "string", description: "Optional title for the session." },
              requirePlanApproval: { type: "boolean", description: "If true, the agent's plan must be explicitly approved." },
              automationMode: { type: "string", enum: ["AUTO_CREATE_PR"], description: "Optional automation mode." },
            },
            required: ["prompt", "source"],
          },
        },
        {
          name: "getSession",
          description: "Get details and status of a specific session.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
            },
            required: ["sessionId"],
          },
        },
        {
          name: "listSessions",
          description: "List recent sessions with optional pagination.",
          inputSchema: {
            type: "object",
            properties: {
              pageSize: { type: "number", description: "Maximum number of sessions to return." },
              pageToken: { type: "string", description: "Token for pagination." },
            },
          },
        },
        {
          name: "approveSessionPlan",
          description: "Approve the latest plan generated by the agent in a session.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
            },
            required: ["sessionId"],
          },
        },
        {
          name: "sendSessionMessage",
          description: "Send a message/prompt to the agent in an existing session.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
              prompt: { type: "string", description: "The message to send to the agent." },
            },
            required: ["sessionId", "prompt"],
          },
        },
        {
          name: "waitForSessionCompletion",
          description: "Poll a session until it reaches a terminal state or timeout.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
              pollInterval: { type: "number", default: 5, description: "Interval in seconds between polls." },
              timeout: { type: "number", default: 600, description: "Maximum time in seconds to wait." },
            },
            required: ["sessionId"],
          },
        },
        {
          name: "getActivity",
          description: "Get details of a specific activity within a session.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
              activityId: { type: "string", description: "The ID of the activity." },
            },
            required: ["sessionId", "activityId"],
          },
        },
        {
          name: "listActivities",
          description: "List activities in a session with optional pagination.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
              pageSize: { type: "number", description: "Maximum number of activities to return." },
              pageToken: { type: "string", description: "Token for pagination." },
            },
            required: ["sessionId"],
          },
        },
        {
          name: "listAllActivities",
          description: "Convenience tool to list all activities in a session by automatically handling pagination.",
          inputSchema: {
            type: "object",
            properties: {
              sessionId: { type: "string", description: "The ID of the session." },
            },
            required: ["sessionId"],
          },
        },
      ],
    }));

    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      const { name, arguments: args } = request.params;

      try {
        switch (name) {
          case "getSource":
            return await this.handleGetSource(args as { sourceId: string });
          case "listSources":
            return await this.handleListSources(args as { filter?: string; pageSize?: number; pageToken?: string });
          case "listAllSources":
            return await this.handleListAllSources(args as { filter?: string });
          case "createSession":
            return await this.handleCreateSession(args as any);
          case "getSession":
            return await this.handleGetSession(args as { sessionId: string });
          case "listSessions":
            return await this.handleListSessions(args as { pageSize?: number; pageToken?: string });
          case "approveSessionPlan":
            return await this.handleApproveSessionPlan(args as { sessionId: string });
          case "sendSessionMessage":
            return await this.handleSendSessionMessage(args as { sessionId: string; prompt: string });
          case "waitForSessionCompletion":
            return await this.handleWaitForSessionCompletion(args as { sessionId: string; pollInterval?: number; timeout?: number });
          case "getActivity":
            return await this.handleGetActivity(args as { sessionId: string; activityId: string });
          case "listActivities":
            return await this.handleListActivities(args as { sessionId: string; pageSize?: number; pageToken?: string });
          case "listAllActivities":
            return await this.handleListAllActivities(args as { sessionId: string });
          default:
            throw new McpError(ErrorCode.MethodNotFound, `Unknown tool: ${name}`);
        }
      } catch (error: any) {
        return {
          content: [
            {
              type: "text",
              text: `Error: ${error.response?.data?.error?.message || error.message || String(error)}`,
            },
          ],
          isError: true,
        };
      }
    });
  }

  // Implementation of handlers
  private async handleGetSource({ sourceId }: { sourceId: string }) {
    // Note: Jules API might use sources/github/owner/repo format
    const name = sourceId.startsWith("sources/") ? sourceId : `sources/${sourceId}`;
    const response = await this.axiosInstance.get(`/${name}`);
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleListSources({ filter, pageSize, pageToken }: { filter?: string; pageSize?: number; pageToken?: string }) {
    const params: any = {};
    if (filter) params.filter = filter;
    if (pageSize) params.pageSize = pageSize;
    if (pageToken) params.pageToken = pageToken;
    const response = await this.axiosInstance.get("/sources", { params });
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleListAllSources({ filter }: { filter?: string }) {
    let allSources: any[] = [];
    let pageToken: string | undefined = undefined;
    do {
      const params: any = {};
      if (filter) params.filter = filter;
      if (pageToken) params.pageToken = pageToken;
      const response: any = await this.axiosInstance.get("/sources", { params });
      allSources = allSources.concat(response.data.sources || []);
      pageToken = response.data.nextPageToken;
    } while (pageToken);
    return { content: [{ type: "text", text: JSON.stringify({ sources: allSources }, null, 2) }] };
  }

  private async handleCreateSession(args: {
    prompt: string;
    source: string;
    startingBranch?: string;
    title?: string;
    requirePlanApproval?: boolean;
    automationMode?: string;
  }) {
    const data: any = {
      prompt: args.prompt,
      sourceContext: {
        source: args.source.startsWith("sources/") ? args.source : `sources/${args.source}`,
      },
    };
    if (args.startingBranch) {
      data.sourceContext.githubRepoContext = { startingBranch: args.startingBranch };
    }
    if (args.title) data.title = args.title;
    if (args.requirePlanApproval !== undefined) data.requirePlanApproval = args.requirePlanApproval;
    if (args.automationMode) data.automationMode = args.automationMode;

    const response = await this.axiosInstance.post("/sessions", data);
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleGetSession({ sessionId }: { sessionId: string }) {
    const name = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    const response = await this.axiosInstance.get(`/${name}`);
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleListSessions({ pageSize, pageToken }: { pageSize?: number; pageToken?: string }) {
    const params: any = {};
    if (pageSize) params.pageSize = pageSize;
    if (pageToken) params.pageToken = pageToken;
    const response = await this.axiosInstance.get("/sessions", { params });
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleApproveSessionPlan({ sessionId }: { sessionId: string }) {
    const name = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    const response = await this.axiosInstance.post(`/${name}:approvePlan`);
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleSendSessionMessage({ sessionId, prompt }: { sessionId: string; prompt: string }) {
    const name = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    const response = await this.axiosInstance.post(`/${name}:sendMessage`, { prompt });
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleWaitForSessionCompletion({ sessionId, pollInterval = 5, timeout = 600 }: { sessionId: string; pollInterval?: number; timeout?: number }) {
    const startTime = Date.now();
    const name = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    
    while (Date.now() - startTime < timeout * 1000) {
      const response = await this.axiosInstance.get(`/${name}`);
      const session = response.data;
      
      // Determine if session is terminal. Jules API documentation doesn't explicitly list terminal states for Session object, 
      // but usually 'outputs' or a completed status field would indicate this.
      // Based on provided curl example, a PR in outputs might be a goal.
      if (session.outputs && session.outputs.length > 0) {
        return { content: [{ type: "text", text: JSON.stringify(session, null, 2) }] };
      }

      await new Promise(resolve => setTimeout(resolve, pollInterval * 1000));
    }
    
    throw new Error(`Timeout waiting for session ${sessionId} to complete.`);
  }

  private async handleGetActivity({ sessionId, activityId }: { sessionId: string; activityId: string }) {
    const sessionName = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    const activityName = activityId.startsWith("activities/") ? activityId : `activities/${activityId}`;
    const response = await this.axiosInstance.get(`/${sessionName}/${activityName}`);
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleListActivities({ sessionId, pageSize, pageToken }: { sessionId: string; pageSize?: number; pageToken?: string }) {
    const sessionName = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    const params: any = {};
    if (pageSize) params.pageSize = pageSize;
    if (pageToken) params.pageToken = pageToken;
    const response = await this.axiosInstance.get(`/${sessionName}/activities`, { params });
    return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
  }

  private async handleListAllActivities({ sessionId }: { sessionId: string }) {
    const sessionName = sessionId.startsWith("sessions/") ? sessionId : `sessions/${sessionId}`;
    let allActivities: any[] = [];
    let pageToken: string | undefined = undefined;
    do {
      const params: any = {};
      if (pageToken) params.pageToken = pageToken;
      const response: any = await this.axiosInstance.get(`/${sessionName}/activities`, { params });
      allActivities = allActivities.concat(response.data.activities || []);
      pageToken = response.data.nextPageToken;
    } while (pageToken);
    return { content: [{ type: "text", text: JSON.stringify({ activities: allActivities }, null, 2) }] };
  }

  async run() {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error("Jules Agent MCP server running on stdio");
  }
}

const server = new JulesAgentServer();
server.run().catch(console.error);
