import type { FunctionComponent } from "preact";
import { Ban, CalendarClock, Check, ExternalLink, RefreshCw, RotateCw, X } from "lucide-preact";
import type { AutomationApprovalRecord, NodeFlowNodeAttemptRecord, NodeFlowNodeRunRecord, NodeFlowRunRecord } from "../../types.js";
import { redactNodeFlowSecrets } from "../../lib/node-flow-view-models.js";
import { Button } from "../ui/Button.js";

interface NodeRunDebuggerProps { runs: NodeFlowRunRecord[]; selectedRunId: string | null; nodeRuns: NodeFlowNodeRunRecord[]; attempts: NodeFlowNodeAttemptRecord[]; approvals?: AutomationApprovalRecord[]; busy?: boolean; onSelectRun: (id: string) => void; onRefresh: () => void; onCancel: () => void; onRetry: () => void; onApprovalDecision?: (approvalId: string, decision: "approve" | "reject") => void; }
const terminal = new Set(["succeeded", "failed", "cancelled"]);
const duration = (start: string | null, end: string | null): string => start ? `${Math.max(0, new Date(end ?? Date.now()).getTime() - new Date(start).getTime())} ms` : "Not started";
export const NodeRunDebugger: FunctionComponent<NodeRunDebuggerProps> = ({ runs, selectedRunId, nodeRuns, attempts, approvals = [], busy, onSelectRun, onRefresh, onCancel, onRetry, onApprovalDecision }) => {
  const run = runs.find((item) => item.id === selectedRunId) ?? runs[0] ?? null;
  return <section className="rounded-[var(--radius-panel)] border border-black/[0.06] bg-white/70 p-4 shadow-[var(--elevation-soft)] dark:border-white/[0.06] dark:bg-white/[0.035]" aria-labelledby="debugger-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-signal-600 dark:text-signal-400">Redacted operations</p><h2 id="debugger-heading" className="text-base font-bold text-slate-900 dark:text-white">Run debugger</h2></div><div className="flex gap-2"><a href="/scheduler" className="inline-flex items-center gap-2 rounded-xl border border-black/[0.08] px-3 py-2 text-sm font-bold text-slate-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-signal-500/40 dark:border-white/[0.08] dark:text-slate-300"><CalendarClock className="h-4 w-4" aria-hidden="true" />Schedule</a><Button size="sm" variant="secondary" icon={RefreshCw} onClick={onRefresh} disabled={busy}>Refresh</Button></div></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[16rem_minmax(0,1fr)]"><div className="flex max-h-80 flex-col gap-2 overflow-auto">{runs.length ? runs.map((item) => <button key={item.id} type="button" onClick={() => onSelectRun(item.id)} aria-current={run?.id === item.id ? "true" : undefined} className="rounded-xl border border-black/[0.06] p-3 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-signal-500/40 dark:border-white/[0.06]"><span className="block text-xs font-bold uppercase text-slate-500">{item.status} · v{item.version}</span><span className="mt-1 block truncate font-mono text-[11px] text-slate-400">{item.id}</span></button>) : <p role="status" className="text-sm text-slate-500">No persisted runs.</p>}</div>
      <div className="min-w-0">{run ? <><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" icon={Ban} onClick={onCancel} disabled={busy || terminal.has(run.status)}>Cancel</Button><Button size="sm" variant="secondary" icon={RotateCw} onClick={onRetry} disabled={busy || !["failed", "cancelled", "attention_required"].includes(run.status)}>Safe retry</Button></div>{approvals.map((approval) => <div key={approval.id} className="mt-3 rounded-xl border border-amber-400/30 bg-amber-400/[0.08] p-3"><p className="text-sm font-bold text-slate-800 dark:text-slate-100">Approval · {approval.nodeId} · {approval.status}</p><p className="mt-1 text-xs text-slate-500">Logical item: {approval.logicalItem}</p>{approval.status === "pending" && onApprovalDecision ? <div className="mt-3 flex gap-2"><Button size="sm" icon={Check} onClick={() => onApprovalDecision(approval.id, "approve")} disabled={busy}>Approve &amp; continue</Button><Button size="sm" variant="secondary" icon={X} onClick={() => onApprovalDecision(approval.id, "reject")} disabled={busy}>Reject</Button></div> : null}</div>)}<p className="mt-3 text-xs text-slate-500">Timing: {duration(run.startedAt, run.finishedAt)} · trigger {run.triggerType}</p><div className="mt-3 grid gap-2">{nodeRuns.map((nodeRun) => <div key={nodeRun.id} className="rounded-xl border border-black/[0.06] p-3 dark:border-white/[0.06]"><p className="text-sm font-bold text-slate-800 dark:text-slate-100">{nodeRun.nodeId} · {nodeRun.status} · {duration(nodeRun.startedAt, nodeRun.finishedAt)}</p>{nodeRun.executionInvocationId ? <a className="mt-1 inline-flex items-center gap-1 text-xs text-signal-600" href={`/?invocation=${encodeURIComponent(nodeRun.executionInvocationId)}`}>Invocation {nodeRun.executionInvocationId}<ExternalLink className="h-3 w-3" aria-hidden="true" /></a> : null}{attempts.filter((attempt) => attempt.nodeRunId === nodeRun.id).map((attempt) => <p key={attempt.id} className="mt-1 text-xs text-slate-500">Attempt {attempt.attemptNumber}: {attempt.status}{attempt.failureClassification ? ` · ${attempt.failureClassification}` : ""}{attempt.retryDecision ? ` · ${attempt.retryDecision}` : ""}</p>)}</div>)}</div><pre className="mt-3 max-h-72 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(redactNodeFlowSecrets(run.output ?? run.input ?? {}), null, 2)}</pre></> : <p className="text-sm text-slate-500">Select a run to inspect its graph state and attempts.</p>}</div></div>
  </section>;
};
